export const SAMPLES = {
  clean: {
    label: 'CLEAN JOB',
    code: `//PAYROLL  JOB (ACCT123),'J SMITH',CLASS=A,MSGCLASS=X,
//             MSGLEVEL=(1,1),NOTIFY=&SYSUID
//STEP010  EXEC PGM=IEFBR14
//DD1      DD   DSN=PROD.PAYROLL.INPUT,DISP=SHR
//DD2      DD   DSN=PROD.PAYROLL.OUTPUT,
//             DISP=(NEW,CATLG,DELETE),
//             SPACE=(CYL,(10,5),RLSE),
//             UNIT=SYSDA,
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=27920)
//STEP020  EXEC PGM=SORT,COND=(4,LT,STEP010)
//SORTIN   DD   DSN=PROD.PAYROLL.OUTPUT,DISP=SHR
//SORTOUT  DD   DSN=PROD.PAYROLL.SORTED,DISP=(NEW,CATLG,DELETE),
//             SPACE=(CYL,(10,5)),UNIT=SYSDA
//SYSOUT   DD   SYSOUT=*
//SYSIN    DD   *
  SORT FIELDS=(1,10,CH,A)
/*
`
  },
  broken: {
    label: 'BROKEN JOB',
    code: `//STEP010  EXEC PGM=IEFBR14
//DD1      DD   DSN=PROD.PAYROLL.INPUT,DISP=SHR
//BADJOB   JOB CLASS=A
//STEP020  EXEC PGM=SORT,REGON=4M
//DD1      DD   DSN=PROD.PAYROLL.OUTPUT,DISP=(NEW,CATLG,DELETE
//DD1      DD   DSN=PROD.PAYROLL.OUTPUT2,DISP=(NEW,CATLG,DELETE)
//BADDD    DD   DUMMY,DSN=SOME.DATASET
//NODATA   DD   DISP=SHR
//STEP030  EXEC PGM=P2,TIME=ABC
//SPBAD    DD   DSN=A.B,DISP=SHR,SPACE=(BADUNIT,(10,5))
//STEP040  EXEC PROC=NOSUCHPROC
//         IF (STEP020.RC = 0) THEN
//STEP050  EXEC PGM=P3
`
  },
  proc: {
    label: 'PROC + SYMBOLICS',
    code: `//MYPROC   PROC LIB=PROD.LOAD,MEM=PGMA
//STEP1    EXEC PGM=&MEM
//STEPLIB  DD   DSN=&LIB,DISP=SHR
//OUT1     DD   DSN=&LIB..OUTPUT,DISP=SHR
//         PEND
//JOBA     JOB (ACCT),'ME',CLASS=A,MSGCLASS=X
//RUN1     EXEC PROC=MYPROC,MEM=PGMB
//STEP1.OUT1  DD DSN=OVERRIDE.DSN,DISP=SHR
//RUN2     EXEC MYPROC,LIB=PROD.LOAD2
//BADOVR   DD   DSN=X.Y,DISP=SHR
//RUN3     EXEC PROC=MYPROC,BADSYM=1
`
  }
};

export const SAMPLE_ORDER = ['clean', 'broken', 'proc'];
